### ISSUE TITLE
Typo on venv_requirements.txt

### ISSUE THREAD

**Issue by gsaker** [gia-guar/JARVIS-ChatGPT#8]
Hi,
Just noticed a typo in venv_requirements. I think `elevnlabslib` should be `elevenlabslib`. I had the following error and this fixed it for me
`ERROR: Could not find a version that satisfies the requirement elevnlabslib (from versions: none)`

**Comment by gia-guar** [comment]
Thanks for raising the issue, It should be fixed now.
